// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScarDetail.API.Infrastructure.Data;

#nullable disable

namespace ScarDetail.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apelido");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("PontoReferencia")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ponto_referencia");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.AgendaBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_hora_inicio");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("motivo");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.ToTable("bloqueios_agenda", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("BufferDeslocamentoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("buffer_deslocamento_minutos");

                    b.Property<DateTime?>("CanceladoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelado_em");

                    b.Property<Guid?>("CanceladoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelado_por_usuario_id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataHoraFimOcupacao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_hora_fim_ocupacao");

                    b.Property<DateTime>("DataHoraFimServico")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_hora_fim_servico");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_hora_inicio");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_minutos");

                    b.Property<string>("EnderecoCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endereco_completo");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uuid")
                        .HasColumnName("endereco_id");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("text")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<string>("ServicoNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("servico_nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorCobrado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_cobrado");

                    b.Property<string>("VeiculoCategoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("veiculo_categoria");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.Property<string>("VeiculoMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("veiculo_marca");

                    b.Property<string>("VeiculoModelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("veiculo_modelo");

                    b.Property<string>("VeiculoPlaca")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("veiculo_placa");

                    b.HasKey("Id");

                    b.HasIndex("CanceladoPorUsuarioId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("PlanoId");

                    b.HasIndex("Status");

                    b.HasIndex("VeiculoId");

                    b.HasIndex("DataHoraInicio", "DataHoraFimOcupacao");

                    b.ToTable("agendamentos", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.AppointmentStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agendamento_id");

                    b.Property<Guid?>("AlteradoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("alterado_por_usuario_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("StatusAnterior")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_anterior");

                    b.Property<string>("StatusNovo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_novo");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("AlteradoPorUsuarioId");

                    b.ToTable("historico_status_agendamento", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.BusinessHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<TimeOnly>("HorarioAbertura")
                        .HasColumnType("time")
                        .HasColumnName("horario_abertura");

                    b.Property<TimeOnly>("HorarioFechamento")
                        .HasColumnType("time")
                        .HasColumnName("horario_fechamento");

                    b.Property<string>("NomeDia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nome_dia");

                    b.HasKey("Id");

                    b.HasIndex("DiaSemana")
                        .IsUnique();

                    b.ToTable("horarios_funcionamento", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Acrescimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("acrescimo");

                    b.Property<Guid>("AgendamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("agendamento_id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("Desconto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("desconto");

                    b.Property<string>("JustificativaAjuste")
                        .HasColumnType("text")
                        .HasColumnName("justificativa_ajuste");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<DateTime>("PagoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("pago_em");

                    b.Property<Guid>("RegistradoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_usuario_id");

                    b.Property<decimal>("Troco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("troco");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_final");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_original");

                    b.Property<decimal>("ValorRecebido")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_recebido");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId")
                        .IsUnique();

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.PermittedNeighborhood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_normalizado");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("NomeNormalizado", "Cidade", "Uf")
                        .IsUnique();

                    b.ToTable("bairros_permitidos", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.PlanAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("acao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_anteriores");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_novos");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("auditoria_planos", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamptz")
                        .HasColumnName("data_expiracao");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("jwt_id");

                    b.Property<bool>("Revogado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("revogado");

                    b.Property<string>("SubstituidoPorToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("substituido_por_token");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.ServicePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_minutos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoCamionete")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_camionete");

                    b.Property<decimal>("PrecoHatch")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_hatch");

                    b.Property<decimal>("PrecoSedan")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_sedan");

                    b.Property<decimal>("PrecoSuv")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_suv");

                    b.Property<decimal>("PrecoWagon")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_wagon");

                    b.HasKey("Id");

                    b.ToTable("planos", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("categoria");

                    b.Property<string>("Cor")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("criado_em");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("veiculos", (string)null);
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Address", b =>
                {
                    b.HasOne("ScarDetail.API.Domain.Entities.User", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.AgendaBlock", b =>
                {
                    b.HasOne("ScarDetail.API.Domain.Entities.User", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPorUsuario");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("ScarDetail.API.Domain.Entities.User", "CanceladoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CanceladoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ScarDetail.API.Domain.Entities.User", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScarDetail.API.Domain.Entities.Address", "Endereco")
                        .WithMany("Agendamentos")
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScarDetail.API.Domain.Entities.ServicePlan", "Plano")
                        .WithMany("Agendamentos")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScarDetail.API.Domain.Entities.Vehicle", "Veiculo")
                        .WithMany("Agendamentos")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanceladoPorUsuario");

                    b.Navigation("Cliente");

                    b.Navigation("Endereco");

                    b.Navigation("Plano");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.AppointmentStatusHistory", b =>
                {
                    b.HasOne("ScarDetail.API.Domain.Entities.Appointment", "Agendamento")
                        .WithMany("HistoricosStatus")
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScarDetail.API.Domain.Entities.User", "AlteradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AlteradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agendamento");

                    b.Navigation("AlteradoPorUsuario");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ScarDetail.API.Domain.Entities.Appointment", "Agendamento")
                        .WithOne("Pagamento")
                        .HasForeignKey("ScarDetail.API.Domain.Entities.Payment", "AgendamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScarDetail.API.Domain.Entities.User", "RegistradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("RegistradoPorUsuario");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.PlanAudit", b =>
                {
                    b.HasOne("ScarDetail.API.Domain.Entities.ServicePlan", "Plano")
                        .WithMany("Auditorias")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScarDetail.API.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plano");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ScarDetail.API.Domain.Entities.User", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("ScarDetail.API.Domain.Entities.User", "Usuario")
                        .WithMany("Veiculos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Address", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("HistoricosStatus");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.ServicePlan", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Auditorias");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.User", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Enderecos");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("ScarDetail.API.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
